# ==============================================================
# CONFIGURACIÓN DE CONEXIÓN ORACLE CLOUD (PROYECTO BCP)
# ==============================================================

# Puerto de la API
server.port=8081

# URL de conexión con la ruta corregida (incluye la carpeta /Wallet/)
spring.datasource.url=jdbc:oracle:thin:@bcpgest_high?TNS_ADMIN=/app/target/classes/Wallet/Wallet_BCPGEST
# Credenciales de Oracle Cloud
spring.datasource.username=ADMIN
spring.datasource.password=Huacaychuco_16

# Driver y Dialecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==============================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# Dialecto específico para Oracle (ayuda a optimizar las consultas)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Optimización de lectura y escritura por lotes (evita viajes innecesarios a la nube)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100

# ==============================================================
# OPTIMIZACIÓN DEL POOL DE CONEXIONES (HIKARICP)
# ==============================================================
# Mantiene conexiones "calientes" para evitar el lag del handshake con la Wallet
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
# 15 segundos máximo intentando conectar antes de dar error
spring.datasource.hikari.connection-timeout=15000
# Mantiene la conexión viva aunque no haya peticiones por 5 minutos
spring.datasource.hikari.idle-timeout=300000

spring.datasource.hikari.auto-commit=true
spring.jpa.properties.hibernate.connection.release_mode=after_transaction